<?php
/**
 * Flexslider : Carrusel Responsivo
 * Esto es un SNIPPET para incluir dentro de una plantilla de página de WP
 * Las imagenes se colocan en la carpeta "images" del directorio del ChildTheme
 * 
 * Javascript:
<script type="text/javascript" charset="utf-8">
  $(window).load(function() {
    $('.flexslider').flexslider({
          animation: "slide",
          controlsContainer: ".flex-container"
    });
  });
</script>

*
* Opciones:
namespace: "flex-",             //{NEW} String: Prefix string attached to the class of every element generated by the plugin
selector: ".slides > li",       //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
animation: "fade",              //String: Select your animation type, "fade" or "slide"
easing: "swing",               //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
direction: "horizontal",        //String: Select the sliding direction, "horizontal" or "vertical"
reverse: false,                 //{NEW} Boolean: Reverse the animation direction
animationLoop: true,             //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
smoothHeight: false,            //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode
startAt: 0,                     //Integer: The slide that the slider should start on. Array notation (0 = first slide)
slideshow: true,                //Boolean: Animate slider automatically
slideshowSpeed: 7000,           //Integer: Set the speed of the slideshow cycling, in milliseconds
animationSpeed: 600,            //Integer: Set the speed of animations, in milliseconds
initDelay: 0,                   //{NEW} Integer: Set an initialization delay, in milliseconds
randomize: false,               //Boolean: Randomize slide order
 
// Usability features
pauseOnAction: true,            //Boolean: Pause the slideshow when interacting with control elements, highly recommended.
pauseOnHover: false,            //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
useCSS: true,                   //{NEW} Boolean: Slider will use CSS3 transitions if available
touch: true,                    //{NEW} Boolean: Allow touch swipe navigation of the slider on touch-enabled devices
video: false,                   //{NEW} Boolean: If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches
 
// Primary Controls
controlNav: true,               //Boolean: Create navigation for paging control of each slide? Note: Leave true for manualControls usage
directionNav: true,             //Boolean: Create navigation for previous/next navigation? (true/false)
prevText: "Previous",           //String: Set the text for the "previous" directionNav item
nextText: "Next",               //String: Set the text for the "next" directionNav item
 
// Secondary Navigation
keyboard: true,                 //Boolean: Allow slider navigating via keyboard left/right keys
multipleKeyboard: false,        //{NEW} Boolean: Allow keyboard navigation to affect multiple sliders. Default behavior cuts out keyboard navigation with more than one slider present.
mousewheel: false,              //{UPDATED} Boolean: Requires jquery.mousewheel.js (https://github.com/brandonaaron/jquery-mousewheel) - Allows slider navigating via mousewheel
pausePlay: false,               //Boolean: Create pause/play dynamic element
pauseText: 'Pause',             //String: Set the text for the "pause" pausePlay item
playText: 'Play',               //String: Set the text for the "play" pausePlay item
 
// Special properties
controlsContainer: "",          //{UPDATED} Selector: USE CLASS SELECTOR. Declare which container the navigation elements should be appended too. Default container is the FlexSlider element. Example use would be ".flexslider-container". Property is ignored if given element is not found.
manualControls: "",             //Selector: Declare custom control navigation. Examples would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
sync: "",                       //{NEW} Selector: Mirror the actions performed on this slider with another slider. Use with care.
asNavFor: "",                   //{NEW} Selector: Internal property exposed for turning the slider into a thumbnail navigation for another slider
 
// Carousel Options
itemWidth: 0,                   //{NEW} Integer: Box-model width of individual carousel items, including horizontal borders and padding.
itemMargin: 0,                  //{NEW} Integer: Margin between carousel items.
minItems: 0,                    //{NEW} Integer: Minimum number of carousel items that should be visible. Items will resize fluidly when below this.
maxItems: 0,                    //{NEW} Integer: Maxmimum number of carousel items that should be visible. Items will resize fluidly when above this limit.
move: 0,                        //{NEW} Integer: Number of carousel items that should move on animation. If 0, slider will move all visible items.
 
// Callback API
start: function(){},            //Callback: function(slider) - Fires when the slider loads the first slide
before: function(){},           //Callback: function(slider) - Fires asynchronously with each slider animation
after: function(){},            //Callback: function(slider) - Fires after each slider animation completes
end: function(){},              //Callback: function(slider) - Fires when the slider reaches the last slide (asynchronous)
added: function(){},            //{NEW} Callback: function(slider) - Fires after a slide is added
removed: function(){}           //{NEW} Callback: function(slider) - Fires after a slide is removed

****************************

IDs de Páginas
--------------
INICI -> 4
DRAG -> 7
DRAGDROID -> 9
CONTACTE -> 13
NOTICIES -> .blog is_frontpage
*/
?>
<!-- *********************  ESTRUCTURA GLOBAL ***************************** -->
<div class="flex-container">
  <div class="flexslider loading">
    <ul class="slides<?php if ( is_404() || is_search() || is_page() && !(is_page(array('4','7','9','13'))) || is_home() || is_single() || is_archive() ) {?> compact_header<?php } ?>">
    <!-- *********************  INICIO ESTRUCTURA GLOBAL ***************************** -->   
	<?php 
    //
    // DIAPO DRAG PROGRAMA *******************************
    //
    ?>
	<?php if ( is_front_page() || is_page(7)) {?>
    <!-- Elige en que pagina aparece >>>>> PÀGINA D'INICI DIAPO 1 -- PÀGINA DRAG ******    -->
    	<!-- ** Si solo hay 1 diapositiva agregar id > li id="onlyslide" -->
        <li <?php if ( is_page(7) ) { ?> id="onlyslide"<?php }?> >
            <span class="img_cover">&nbsp;</span>
            <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_programa.jpg" alt="<?php if( qtrans_getLanguage() == 'es' ){?>DRAG Dispositvo de Recursos para Agentes <?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>DRAG Dispositiu de Recursos per Agents <?php }else { ?>DRAG <?php } ?>" class="img_fullback" />
            <?php
                if( qtrans_getLanguage() == 'es' ){ ?>
                    <div class="flex-caption">
                        <h2>DRAG es el Dispositivo de Recursos para Agentes <br/ >que soluciona la gestión informática de tu policía local <br/ >de forma eficiente, ágil y cómoda.</h2>
                        <p>Con un extraordinario servicio postventa, a tu disposición los 365 días del año.</p>
                        <p>Estamos especializados en la informatización de cuerpos de seguridad <br/ >y emergencias: <em>Policía Local, Vigilancia Municipal, Protección Civil y Bomberos</em>.
</p>
                        <?php if ( is_front_page() ) { ?>
                        <div class="mockup"><a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/drag-policia-local/' ; ?>" target="_self" class="mockup_wrapper"  title="DRAG Dispositivo de Recursos para Agentes"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag.png" alt="DRAG: Video Demostrativo" class="mockup_base" /><span class="mockup_screen mockup_banner"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag_screen_banner.jpg" alt="DRAG Dispositivo de Recursos para Agentes" /></span></a></div>
                        <!-- CALL TO ACT HOME -->
                        <a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/drag-policia-local/' ; ?>" target="_self" class="calltoact bluebutton" title="DRAG Dispositivo de Recursos para Agentes">DESCUBRE SUS VENTAJAS <i class="icon-chevron-right"></i></a>
                        <?php } elseif ( is_page(7)  ) {?>
                        <div class="mockup"><span class="mockup_wrapper"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag.png" alt="DRAG: Vídeo Explicativo" class="mockup_base" />
                        	<a href="http://www.youtube.com/embed/mvrwWARe9sw?wmode=transparent&rel=0&iframe=true&showinfo=0;autoplay=1;color=white;" target="_blank" title="DRAG Vídeo Explicativo" class="mockup_screen novideo"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag_screen_novideo_es.jpg" alt="DRAG: Vídeo Explicativo" /></a>
                            <a href="http://www.youtube.com/embed/mvrwWARe9sw?wmode=transparent&rel=0&iframe=true&showinfo=0;autoplay=1;color=white;" target="_blank" title="DRAG Vídeo Explicativo" class="mockup_screen video_es"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag_screen_video_es.jpg" alt="DRAG: Vídeo Explicativo" /></a>
                        </span></div>
                        <!-- CALL TO ACT PROGRAMA -->
                        <a href="#caracteristicas" class="calltoact nocolor scroll">VENTAJAS Y CARACTERÍSTICAS <i class="icon-chevron-down"></i></a>
                        <?php }?>
                    </div>
                <?php }elseif( qtrans_getLanguage() == 'ca' ){ ?>
                    <div class="flex-caption">
                        <h2>DRAG és el Dispositiu de Recursos per Agents <br />que soluciona la gestió informàtica de la teva policia local <br />de forma eficient, àgil i còmode.</h2>
                        <p>Amb un extraordinari servei postvenda, a la teva disposició els 365 dies de l’any.</p>
                        <p>Estem especialitzats en el programari de suport informàtic a cossos de seguretat <br />i emergències: <em>Policia Local, Vigilància Municipal, Protecció Civil i Bombers</em>.
</p>
                        <?php if ( is_front_page() ) { ?>
                        <div class="mockup"><a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/drag-policia-local/' ; ?>" target="_self" class="mockup_wrapper" title="DRAG Dispositiu de Recursos per Agents"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag.png" alt="DRAG: Video Explicatiu" class="mockup_base" /><span class="mockup_screen mockup_banner"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag_screen_banner.jpg" alt="DRAG Dispositiu de Recursos per Agents" /></span></a></div>
                        <!-- CALL TO ACT HOME -->
                        <a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/drag-policia-local/' ; ?>" target="_self" class="calltoact bluebutton" title="DRAG Dispositiu de Recursos per Agents">DESCOBRIU ELS SEUS AVANTATGES <i class="icon-chevron-right"></i></a>
                        <?php } elseif ( is_page(7)  ) {?>
                        <div class="mockup"><span class="mockup_wrapper"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag.png" alt="DRAG: Video Explicatiu" class="mockup_base" />
                        	<a href="http://www.youtube.com/embed/mwuYNfZ8VXE?wmode=transparent&rel=0&iframe=true&showinfo=0;autoplay=1;color=white;" target="_blank" title="DRAG: Video Explicatiu" class="mockup_screen novideo"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag_screen_novideo_ca.jpg" alt="DRAG: Video Explicatiu" /></a>
                            <a href="http://www.youtube.com/embed/mwuYNfZ8VXE?wmode=transparent&rel=0&iframe=true&showinfo=0;autoplay=1;color=white;" target="_blank" title="DRAG: Video Explicatiu" class="mockup_screen video_cat"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag_screen_video_ca.jpg" alt="DRAG: Video Explicatiu" /></a>
                        </span></div>
                        <!-- CALL TO ACT PROGRAMA -->
                        <a href="#caracteristicas" target="_self" class="calltoact nocolor scroll">AVANTATGES I CARACTERÍSTIQUES <i class="icon-chevron-down"></i></a>
                        <?php }?>
                    </div>
                <?php }elseif( qtrans_getLanguage() == 'en' ){ ?>
                    <div class="flex-caption">
                        <h2>DRAG és el Dispositiu de Recursos per Agents <br />que soluciona la gestió informàtica de la teva policia local <br />de forma eficient, àgil i còmode.</h2>
                        <p>Amb un extraordinari servei postvenda, a la teva disposició els 365 dies de l’any.</p>
                        <p>Estem especialitzats en el programari de suport informàtic a cossos de seguretat <br />i emergències: <em>Policia Local, Vigilància Municipal, Protecció Civil i Bombers</em>.
</p>
                        <?php if ( is_front_page() ) { ?>
                        <!-- CALL TO ACT HOME -->
                        <div class="mockup"><a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/drag-policia-local/' ; ?>" target="_self" class="mockup_wrapper" title="DRAG "><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag.png" alt="DRAG" class="mockup_base" /><span class="mockup_screen mockup_banner"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag_screen_banner.jpg" alt="DRAG" /></span></a></div>
                        <a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/drag-policia-local/' ; ?>" target="_self" class="calltoact bluebutton" title="DRAG ">SEE KEY GFEATURES <i class="icon-chevron-right"></i></a>
                        <?php } elseif ( is_page(7)  ) {?>
                        <div class="mockup"><span class="mockup_wrapper"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag.png" alt="DRAG: Showreel Video" class="mockup_base" />
                        	<a href="http://www.youtube.com/embed/mwuYNfZ8VXE?wmode=transparent&rel=0&iframe=true&showinfo=0;autoplay=1;color=white;" target="_blank" title="DRAG: Showreel Video" class="mockup_screen novideo"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag_screen_novideo_en.jpg" alt="DRAG: Showreel Video" /></a>
                            <a href="http://www.youtube.com/embed/mwuYNfZ8VXE?wmode=transparent&rel=0&iframe=true&showinfo=0;autoplay=1;color=white;" target="_blank" title="DRAG: Showreel Video" class="mockup_screen video_en"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag_screen_video_en.jpg" alt="DRAG: Showreel Video" /></a>
                        </span></div>
                        <!-- CALL TO ACT PROGRAMA -->
                        <a href="#caracteristicas" target="_self" class="calltoact nocolor scroll">KEYS AND FEATURES <i class="icon-chevron-down"></i></a>
                        <?php }?>
                    </div>
                <!-- // qtranslate text multidioma -->
                <?php } ?>
      	</li>
    <?php 
    //
    // DIAPO DRAGDROID *******************************
    //
    ?>
	<?php }
	if ( is_front_page() || is_page(9)) {?>
    <!-- Elige en que pagina aparece >>>>> PÀGINA D'INICI DIAPO 2 -- PÀGINA DRAGDROID ******    -->
    	<!-- ** Si solo hay 1 diapositiva agregar id > li id="onlyslide" -->
        <li <?php if ( is_page(9) ) { ?> id="onlyslide"<?php }?> >
            <span class="img_cover">&nbsp;</span>
            <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_dragdroid.jpg" alt="<?php if( qtrans_getLanguage() == 'es' ){?>DRAGDROID Android App <?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>DRAGDROID Android App <?php }else { ?>DRAGDROID Android App <?php } ?>" class="img_fullback" />
            <?php
                if( qtrans_getLanguage() == 'es' ){ ?>
                    <div class="flex-caption">
                        <h2>DRAGDroid es una aplicación para terminales móviles <br />(teléfonos o tabletas) que conectan con el programa <br />DRAG instalado en jefatura.</h2>
                        <p>Permite que mandos, agentes y personal autorizado accedan a la información <br />de forma segura, rápida y en tiempo real: <em>novedades, disciplina vial <br />y cuadrante de servicio</em>.</p>
                        <?php if ( is_front_page() ) { ?>
                        <!-- CALL TO ACT HOME -->
                        <div class="mockup"><a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/dragdroid-app-policia-local/' ; ?>" target="_self" class="mockup_wrapper" title="DRAGDROID Android App"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_dragdroid.png" alt="DRAGDROID Android App" class="mockup_base" /></a></div>
                        <a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/dragdroid-app-policia-local/' ; ?>" target="_self" class="calltoact bluebutton" title="DRAGDROID Android App">CONOCE NUESTRA APP <i class="icon-chevron-right"></i></a>
                        <?php } elseif ( is_page(9)  ) {?>
                        <!-- CALL TO ACT PROGRAMA -->
                        <div class="mockup"><span class="mockup_wrapper"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_dragdroid.png" alt="DRAGDROID Android App" class="mockup_base" /><span class="mockup_screen_dd mockup_banner"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_dragdroid_screen.gif" alt="DRAGDROID Android App" class="mockup_base" /></span></span></div>
                        <a href="#caracteristicas" target="_self" class="calltoact nocolor scroll">VENTAJAS Y CARACTERÍSTICAS <i class="icon-chevron-down"></i></a>
                        <?php }?>
                    </div>
                <?php }elseif( qtrans_getLanguage() == 'ca' ){ ?>
                    <div class="flex-caption">
                        <h2>DRAGDroid és una aplicació per a terminals mòbils <br />(telèfons o tablets)  que connecta amb el programa <br />DRAG instal·lat a la prefectura.</h2>
                        <p>Permet a comandaments, agents i personal autoritzat accedir a la informació <br />de forma segura, ràpida i en temps real: <em>novetats, disciplina viària <br />i quadrant de servei</em>.</p>
                        <?php if ( is_front_page() ) { ?>
                        <!-- CALL TO ACT HOME -->
                        <div class="mockup"><a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/dragdroid-app-policia-local/' ; ?>" target="_self" class="mockup_wrapper" title="DRAGDROID Android App"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_dragdroid.png" alt="DRAGDROID Android App" class="mockup_base" /></a></div>
                        <a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/dragdroid-app-policia-local/' ; ?>" target="_self" class="calltoact bluebutton" title="DRAGDROID Android App">CONEIX LA NOSTRA APP <i class="icon-chevron-right"></i></a>
                        <?php } elseif ( is_page(9)  ) {?>
                        <!-- CALL TO ACT PROGRAMA -->
                        <div class="mockup"><span class="mockup_wrapper"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_dragdroid.png" alt="DRAGDROID Android App" class="mockup_base" /><span class="mockup_screen_dd mockup_banner"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_dragdroid_screen.gif" alt="DRAGDROID Android App" class="mockup_base" /></span></span></div>
                        <a href="#caracteristicas" target="_self" class="calltoact nocolor scroll">AVANTATGES I CARACTERÍSTIQUES <i class="icon-chevron-down"></i></a>
                        <?php }?>
                    </div>
                <?php }elseif( qtrans_getLanguage() == 'en' ){ ?>
                    <div class="flex-caption">
                        <h2>DRAGDroid it's an App per a terminals mòbils <br />(telèfons o tablets)  que connecta amb el programa <br />DRAG instal·lat a la prefectura.</h2>
                        <p>Permet a comandaments, agents i personal autoritzat accedir a la informació <br />de forma segura, ràpida i en temps real: <em>novetats, disciplina viària <br />i quadrant de servei</em>.</p>
                        <?php if ( is_front_page() ) { ?>
                        <!-- CALL TO ACT HOME -->
                        <div class="mockup"><a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/dragdroid-app-policia-local/' ; ?>" target="_self" class="mockup_wrapper" title="DRAGDROID Android App"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_dragdroid.png" alt="DRAGDROID Android App" class="mockup_base" /></a></div>
                        <a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/dragdroid-app-policia-local/' ; ?>" target="_self" class="calltoact bluebutton" title="DRAGDROID Android App">realize its ventages <i class="icon-chevron-right"></i></a>
                        <?php } elseif ( is_page(9)  ) {?>
                        <div class="mockup"><span class="mockup_wrapper"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_dragdroid.png" alt="DRAGDROID Android App" class="mockup_base" /><span class="mockup_screen_dd mockup_banner"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_dragdroid_screen.gif" alt="DRAGDROID Android App" class="mockup_base" /></span></span></div>
                        <!-- CALL TO ACT PROGRAMA -->
                        <a href="#caracteristicas" target="_self" class="calltoact nocolor scroll">ventages and characteristichs <i class="icon-chevron-down"></i></a>
                        <?php }?>
                    </div>
                <!-- // qtranslate text multidioma -->
                <?php } ?>
        </li>
    <?php 
    //
    // DIAPO CONTACTE *******************************
    //
    ?>
	<?php }
	if ( is_page(13)) {?>
    <!-- //
    Elige en que pagina aparece >>>>> PAGINA DE CONTACTO ************************************
    -->
    	<!-- ** Si solo hay 1 diapositiva agregar id > li id="onlyslide" -->
        <li id="onlyslide">
            <span class="img_cover">&nbsp;</span>
            <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_contacte.jpg" alt="<?php if( qtrans_getLanguage() == 'es' ){?>DRAG > CONTACTO <?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>DRAG > CONTACTE <?php }else { ?>DRAG > CONTACT <?php } ?>" class="img_fullback" />
            <div class="flex-caption caption-contact">
                <article class="box vies_contact">
                    <header>
                        <h1><?php if( qtrans_getLanguage() == 'es' ){?>Vías de Contacto<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>Víes de Contacte<?php }else { ?>Contact Us<?php } ?></h1>
                    </header>
                    <section>
                        <ul>
                            <li><i class="icon-envelope pull-left"></i><b><?php if( qtrans_getLanguage() == 'es' ){?>Correo Electrónico<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>Correu Electrònic<?php }else { ?>e-Mail<?php } ?></b> <br />info<span>&nbsp;</span>&#64;<span>&nbsp;</span>drag.<?php if( qtrans_getLanguage() == 'es' ){?>es<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>cat<?php }else { ?>es<?php } ?></li>
                            <li><i class="icon-phone pull-left"></i><b><?php if( qtrans_getLanguage() == 'es' ){?>Teléfono<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>Telèfon<?php }else { ?>Phone<?php } ?></b> <br />931 145 837</li>
                        </ul>
                        <ul>
                            <li><i class="icon-user pull-left"></i><b><?php if( qtrans_getLanguage() == 'es' ){?>Departamento Comercial<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>Departament Comercial<?php }else { ?>Sales Dept.<?php } ?></b> <br />jordi.closas<span>&nbsp;</span>&#64;<span>&nbsp;</span>drag.<?php if( qtrans_getLanguage() == 'es' ){?>es<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>cat<?php }else { ?>es<?php } ?></li>
                            <li><i class="icon-user-md pull-left"></i><b><?php if( qtrans_getLanguage() == 'es' ){?>Departamento Técnico<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>Departament Tècnic<?php }else { ?>Technical Dept.<?php } ?></b> <br />alexandre.fillat<span>&nbsp;</span>&#64;<span>&nbsp;</span>drag.<?php if( qtrans_getLanguage() == 'es' ){?>es<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>cat<?php }else { ?>es<?php } ?></li>
                        </ul>
                        <div class="clearboth"></div>
                    </section>
                    <footer>
                        <p><?php if( qtrans_getLanguage() == 'es' ){?>SERVICIO TÉCNICO ONLINE<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>SERVEI TÈCNIC ONLINE<?php }else { ?>ONLINE SUPPORT<?php } ?></p>
                        <!-- ISL Pronto -->
                        <a id="islpronto_link" href="mailto:alexandre.fillat@drag.es">
                        	<img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/<?php if( qtrans_getLanguage() == 'es' ){?>es<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>ca<?php }else { ?>en<?php } ?>/islpronto-message.jpg" id="islpronto_image" border="0" alt="<?php if( qtrans_getLanguage() == 'es' ){?>Chat OnLine<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>Xat OnLine<?php }else { ?>OnLine Chat<?php } ?>" />
                        </a>
                        <!-- script al footer -->
                        <!-- ISL Pronto -->
                        <div class="clearboth"></div> 
                    </footer>
                </article>
			<?php if( qtrans_getLanguage() == 'es' ){ ?>
                <h2>QUIÉNES SOMOS</h2>
                <h4 class="header-directrius">Nuestra experiencia se fundamenta en la dedicación y el resultado de más de 20 años trabajando en el sector público municipal a nivel de tratamiento y mecanización de datos, así como su gestión, exportación y evaluación estadística.</h4>
                <div class="contact-directrius">
                    <p>Las directrices de desarrollo de nuestros proyectos informáticos son la <em>investigación constante para incorporar nuevos sistemas tecnológicos al servicio de las Policías Locales</em>.</p>
                    <p>Apostamos por la creación de entornos gráficos claros e intuitivos, adaptándolos a un programa dinámico que <em>evoluciona en sintonía con las diferentes necesidades de las personas que lo utilizan</em>.</p>
                </div>
                <span class="directrius-more"><i class="icon-plus-sign icon-large"></i></span>
                <span class="caption_space_contact"></span>
            <?php }elseif( qtrans_getLanguage() == 'ca' ){ ?>
                <h2>QUI SOM?</h2>
                <h4 class="header-directrius">La nostra experiència es fonamenta en la dedicació i el resultat de més de 20 anys treballant en el sector públic municipal a nivell de tractament i mecanització de dades, així com la seva gestió, exportació i avaluació estadística.</h4>
                <div class="contact-directrius">
                    <p>Les directrius de desenvolupament dels nostres projectes informàtics són la <em>investigació constant per incorporar nous sistemes tecnològics al servei de les Policies Locals</em>.</p>
                    <p>Apostem per la creació d’entorns gràfics clars i intuïtius, adaptant-los a un programari dinàmic que <em>evoluciona en sintonia amb les diferents necessitats de les persones que l’utilitzen</em>.</p>
                </div>
                <span class="directrius-more"><i class="icon-plus-sign icon-large"></i></span>
                <span class="caption_space_contact"></span>
            <?php }elseif( qtrans_getLanguage() == 'en' ){ ?>
                <h2>WHO WE ARE?</h2>
                <h4 class="header-directrius">La nostra experiència es fonamenta en la dedicació i el resultat de més de 20 anys treballant en el sector públic municipal a nivell de tractament i mecanització de dades, així com la seva gestió, exportació i avaluació estadística.</h4>
                <div class="contact-directrius">
                	<p>Les directrius de desenvolupament dels nostres projectes informàtics són la <em>investigació constant per incorporar nous sistemes tecnològics al servei de les policies locals</em>.</p>
                	<p>Apostem per la creació d’entorns gràfics clars i intuïtius, adaptant-los a un programari dinàmic que <em>evoluciona en sintonia amb les diferents necessitats de les persones que l’utilitzen</em>.</p>
                </div>
                <span class="directrius-more"><i class="icon-plus-sign icon-large"></i></span>
                <span class="caption_space_contact"></span>
                <!-- // qtranslate text multidioma -->
            <?php } ?>
            </div>    
        </li>
	<?php }
	//
    // HEADER HOME NOTICIAS *******************************
    //
    ?>
	<?php if ( is_home() ) {?>
    <!-- Elige en que pagina aparece >>>>> Páginas de Noticias ******    -->
    	<!-- ** Si solo hay 1 diapositiva agregar id > li id="onlyslide" -->
        <li id="onlyslide">
            <span class="img_cover">&nbsp;</span>
            <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_header_global.jpg" alt="<?php if( qtrans_getLanguage() == 'es' ){?>DRAG Dispositvo de Recursos para Agentes <?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>DRAG Dispositiu de Recursos per Agents <?php }else { ?>DRAG <?php } ?>" class="img_fullback" />
            <div class="flex-caption caption-postcat">
                <?php global $page, $paged; ?>
                <h2>
                    <?php echo get_the_title(11); ?>
                </h2>
                <p>
                	<?php if( qtrans_getLanguage() == 'es' ){
					$metafield = get_post_meta(11, 'metadescription_es', true);
					}elseif( qtrans_getLanguage() == 'ca' ){
					$metafield = get_post_meta(11, 'metadescription_ca', true);
					}else{
					$metafield = get_post_meta(11, 'metadescription_en', true);
					}
					if (!empty ($metafield)){ $content = $metafield;
						}else{ $content = get_bloginfo('description');} 
						echo $content;
						?>      
                </p>
            <!-- MOCKUPS GLOBAL -->
                <div class="mockup">
                    <span class="mockup_wrapper">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_dragdroid.png" alt="DRAGDROID Android App" class="mockup_base" />
                    </span>
                    <span class="mockup_wrapper">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag.png" alt="DRAG" class="mockup_base" />
                        <span class="mockup_screen mockup_banner"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag_screen_banner.jpg" alt="<?php if( qtrans_getLanguage() == 'es' ){ ?>DRAG Dispositivo de Recursos para Agentes<?php }elseif( qtrans_getLanguage() == 'ca' ){ ?>DRAG Dispositiu de Recursos para Agents<?php }elseif( qtrans_getLanguage() == 'en' ){ ?>DRAG Dispositivo de Recursos para Agentes<?php } ?>" /></span>
                    </span>
                </div>
        	</div>
        </li>
    <?php }
    //
    // HEADER SINGLE POST *******************************
    //
    ?>
	<?php if ( is_single() && !is_attachment() ) {?>
    <!-- Elige en que pagina aparece >>>>> Páginas de Posts ******    -->
    	<!-- ** Si solo hay 1 diapositiva agregar id > li id="onlyslide" -->
        <li id="onlyslide">
            <span class="img_cover">&nbsp;</span>
			<?php global $post;
            $category = get_the_category();
			$category_id = $category[0]->cat_ID;
            if ( $category_id == 3 ) { //CATEGORIA DRAG 
                // load all 'category' terms for the post ?> 
                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_noticies_drag.jpg" alt="<?php echo _e($category[0]->category_description, 'qtranslate'); ?>" class="img_fullback" />
            <?php }elseif ( $category_id == 4 ) { //CATEGORIA DRAGDROID 
                // load all 'category' terms for the post ?> 
                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_noticies_dragdroid.jpg" alt="<?php echo _e($category[0]->category_description, 'qtranslate'); ?>" class="img_fullback" />
            <?php }elseif ( $category_id == 5 ) { //CATEGORIA SEGURETAT CIUTADANA 
                // load all 'category' terms for the post ?> 
                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_noticies_seguretat.jpg" alt="<?php echo _e($category[0]->category_description, 'qtranslate'); ?>" class="img_fullback" />
            <?php }elseif ( $category_id == 13 ) { //CATEGORIA EMPRESA DRAGCLIC 
                // load all 'category' terms for the post ?> 
                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_noticies_empresa.jpg" alt="<?php echo _e($category[0]->category_description, 'qtranslate'); ?>" class="img_fullback" />
            <?php }else{ //Resta de Categories 
                // load all 'category' terms for the post ?> 
                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_header_global.jpg" alt="<?php echo _e($category[0]->category_description, 'qtranslate'); ?>" class="img_fullback" />
            <?php } ?>
            <div class="flex-caption caption-postcat">
                <h2><?php the_title(); ?></h2>
                <p><?php global $post;
                    $category = get_the_category($post->ID); 
                    // load all 'category' terms for the post
                    $terms = get_the_terms($post->ID, 'category');
                    // we will use the first term to load ACF data from 
                    if( !empty($terms) )
                    {
                        $term = array_pop($terms);
                        $iconcat = get_field('cat_icon', 'category_' . $term->term_id );		 
                    }
                    echo '<a href="' . get_category_link($category[0]->term_id ) . '" target="_self" title="' .  $category[0]->cat_name . '"> <em style="text-transform:uppercase"><i class="' . $iconcat . '"></i>&nbsp;&nbsp;' .  $category[0]->cat_name . '</a>';
                    ?></em>
                    &nbsp;<i class="icon-angle-right"></i>&nbsp;&nbsp;<?php echo _e($category[0]->category_description, 'qtranslate'); ?>
                </p>
            <!-- MOCKUPS GLOBAL -->
                <div class="mockup">
                    <span class="mockup_wrapper">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_dragdroid.png" alt="DRAGDROID Android App" class="mockup_base" />
                    </span>
                    <span class="mockup_wrapper">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag.png" alt="DRAG: Video Demostrativo" class="mockup_base" />
                        <span class="mockup_screen mockup_banner"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag_screen_banner.jpg" alt="<?php if( qtrans_getLanguage() == 'es' ){ ?>DRAG Dispositivo de Recursos para Agentes<?php }elseif( qtrans_getLanguage() == 'ca' ){ ?>DRAG Dispositiu de Recursos para Agents<?php }elseif( qtrans_getLanguage() == 'en' ){ ?>DRAG Dispositivo de Recursos para Agentes<?php } ?>" /></span>
                    </span>
                </div>
        	</div>
        </li>
    <?php }
    //
    // HEADER CATEGORY *******************************
    //
    ?>
	<?php if ( is_category() ) {?>
    <!-- Elige en que pagina aparece >>>>> Páginas de Categoría ******    -->
    	<!-- ** Si solo hay 1 diapositiva agregar id > li id="onlyslide" -->
        <li id="onlyslide">
            <span class="img_cover">&nbsp;</span>
			<?php
            if ( is_category( '3' ) ) { //CATEGORIA DRAG ?>
                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_noticies_drag.jpg" alt="<?php $content = apply_filters('archive_meta', category_description(), 'qtranslate'); echo strip_tags($content); ?>" class="img_fullback" />
            <?php }elseif ( is_category( '4' ) ) { //CATEGORIA DRAGDROID ?> 
                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_noticies_dragdroid.jpg" alt="<?php $content = apply_filters('archive_meta', category_description(), 'qtranslate'); echo strip_tags($content); ?>" class="img_fullback" />
            <?php }elseif ( is_category( '5' ) ) { //CATEGORIA SEGURETAT CIUTADANA  ?>
                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_noticies_seguretat.jpg" alt="<?php $content = apply_filters('archive_meta', category_description(), 'qtranslate'); echo strip_tags($content); ?>" class="img_fullback" />
            <?php }elseif ( is_category( '13' ) ) { //CATEGORIA EMPRESA DRAGCLIC ?>
                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_noticies_empresa.jpg" alt="<?php $content = apply_filters('archive_meta', category_description(), 'qtranslate'); echo strip_tags($content); ?>" class="img_fullback" />
            <?php }else{ //Resta de Categories ?>
                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_header_global.jpg" alt="<?php $content = apply_filters('archive_meta', category_description(), 'qtranslate');  echo strip_tags($content); ?>" class="img_fullback" />
            <?php } ?>
            <div class="flex-caption caption-postcat">
                <h2>
                	<?php 
					$queried_object = get_queried_object(); 
					$taxonomy = $queried_object->taxonomy;
					$term_id = $queried_object->term_id; 
                    // we will use the first term to load ACF data from 
					$iconcat = get_field('cat_icon', $taxonomy . '_' . $term_id);
					?>
                	<i class="<?php echo $iconcat ?>"></i>&nbsp;
                    <?php if( qtrans_getLanguage() == 'es' ){ $content_h = 'Categoría: ';
					}elseif( qtrans_getLanguage() == 'ca' ){ $content_h = 'Categoria: ';
					}elseif( qtrans_getLanguage() == 'en' ){ $content_h = 'Category: ';
					} ?>
                    <?php echo $content_h; ?><em><?php single_cat_title(); ?> </em>
                </h2>
                <p><?php if ( !(''== category_description()) ) : $content = apply_filters('archive_meta', category_description(), 'qtranslate'); endif; echo strip_tags($content);?></p>
            <!-- MOCKUPS GLOBAL -->
                <div class="mockup">
                    <span class="mockup_wrapper">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_dragdroid.png" alt="DRAGDROID Android App" class="mockup_base" />
                    </span>
                    <span class="mockup_wrapper">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag.png" alt="DRAG: Video Demostrativo" class="mockup_base" />
                        <span class="mockup_screen mockup_banner"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag_screen_banner.jpg" alt="<?php if( qtrans_getLanguage() == 'es' ){ ?>DRAG Dispositivo de Recursos para Agentes<?php }elseif( qtrans_getLanguage() == 'ca' ){ ?>DRAG Dispositiu de Recursos para Agents<?php }elseif( qtrans_getLanguage() == 'en' ){ ?>DRAG Dispositivo de Recursos para Agentes<?php } ?>" /></span>
                    </span>
                </div>
        	</div>
        </li>
	<?php }
    //
    // HEADER COMPACTE MULTIUS *******************************
    //
    ?>
	<?php 
	if ( is_404() || is_search() || is_page() && !(is_page(array('4','7','9','13'))) || is_tag() || is_archive() && !(is_category()) || is_attachment() ) {?>
    <!-- Elige en que pagina aparece >>>>> Multipagina ******    -->
    	<!-- ** Si solo hay 1 diapositiva agregar id > li id="onlyslide" -->
        <li id="onlyslide">
            <span class="img_cover">&nbsp;</span>
            <?php if ( is_author() ){ ?>
            <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_noticies_empresa.jpg" alt="<?php if( qtrans_getLanguage() == 'es' ){?>DRAG DRAGDROID Policía Local<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>DRAG DRAGDROID Policia Local<?php }else { ?>DRAG DRAGDROID Policia Local<?php } ?>" class="img_fullback" />
            <?php }elseif ( is_page(25) ){ ?>
            <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_noticies_empresa.jpg" alt="<?php if( qtrans_getLanguage() == 'es' ){?>DRAG DRAGDROID Policía Local<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>DRAG DRAGDROID Policia Local<?php }else { ?>DRAG DRAGDROID Policia Local<?php } ?>" class="img_fullback" />
			<?php }else{ ?>
            <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slides/drag_header_global.jpg" alt="<?php if( qtrans_getLanguage() == 'es' ){?>DRAG DRAGDROID Policia Local<?php }elseif( qtrans_getLanguage() == 'ca' ) { ?>DRAG DRAGDROID Policía Local<?php }else { ?>DRAG DRAGDROID Policia Local<?php } ?>" class="img_fullback" />
            <?php } ?>
            <div class="flex-caption <?php if (is_archive() || is_attachment()) {?> caption-postcat<?php } ?>">
			<?php 
			if ( is_404() ){ ?>
                <!-- 404 CAPTION -->
                <h2>
                    <?php if( qtrans_getLanguage() == 'es' ){ ?>LA PÁGINA NO EXISTE
                    <?php }elseif( qtrans_getLanguage() == 'ca' ){ ?>LA PÀGINA NO EXISTEIX
                    <?php }elseif( qtrans_getLanguage() == 'en' ){ ?>PAGE NOT FOUND
                    <?php } ?>
                </h2>
                <p>
                    <?php if( qtrans_getLanguage() == 'es' ){ ?>Lo sentimos pero no encontramos este contenido
                    <?php }elseif( qtrans_getLanguage() == 'ca' ){ ?>Ho sentim però no trobem aquest contingut
                    <?php }elseif( qtrans_getLanguage() == 'en' ){ ?>Sorry but we can't find this page
                    <?php } ?>
                </p>
            <?php }elseif ( is_search() ){ ?>
            	<!-- Search CAPTION -->
                <h2>
                    <i class="icon-search"></i>&nbsp;
					<?php the_search_query(); ?>
                </h2>
                <p>
                    <?php if( qtrans_getLanguage() == 'es' ){ ?>Resultados de BÚSQUEDA
                    <?php }elseif( qtrans_getLanguage() == 'ca' ){ ?>Resultats de la CERCA
                    <?php }elseif( qtrans_getLanguage() == 'en' ){ ?>SEARCH RESULTS
                    <?php } ?>
                </p>
            <?php }elseif ( is_page() && !(is_attachment()) ){ ?>
            	<!-- Page CAPTION -->
                <h2>
                    <?php the_title(); ?>
                </h2>
                <p>
                	<?php if( qtrans_getLanguage() == 'es' ){
					$metafield = get_post_meta(get_the_ID(), 'metadescription_es', true);
					}elseif( qtrans_getLanguage() == 'ca' ){
					$metafield = get_post_meta(get_the_ID(), 'metadescription_ca', true);
					}else{
					$metafield = get_post_meta(get_the_ID(), 'metadescription_en', true);
					}
					if (!empty ($metafield)){ $content = $metafield;
						}else{ $content = get_bloginfo('name') . " | " . get_bloginfo('description');} 
						echo $content;
						?>      
                </p>
			<?php }elseif ( is_tag() ){ ?>
            	<!-- Tag CAPTION -->
                <h2>
                    <i class="icon-tag"></i>&nbsp;
					<em><?php single_tag_title(); ?></em>
                </h2>
                <p>
                	<?php if( qtrans_getLanguage() == 'es' ){ ?> 
					Archivo de Noticias relacionadas con la temática <em><?php single_tag_title(); ?></em>.
					<?php }elseif( qtrans_getLanguage() == 'ca' ){ ?>
					Arxiu de Notícies vinculades a la temàtica <em><?php single_tag_title(); ?></em>.
					<?php }else{ ?>
					Posts Arxive relating the subject <em><?php single_tag_title(); ?></em>.
                    <?php } ?>
                </p>
            <?php }elseif ( is_date() ){ ?>
            	<!-- Date CAPTION -->
                <h2>
                    <i class="icon-calendar"></i>&nbsp;
					<?php if  (is_day()) { global $post; echo get_the_time(get_option('date_format')); ?>
                    <?php }elseif  (is_month()) { global $post; echo get_the_time('F Y'); ?>
                    <?php }elseif  (is_year()) { global $post; echo get_the_time('Y'); ?>
                    <?php } ?>
                </h2>
                <p>
                	<?php if( qtrans_getLanguage() == 'es' ){ ?> 
					Archivo cronológico de Noticias.
					<?php }elseif( qtrans_getLanguage() == 'ca' ){ ?>
					Arxiu de cronològic de Notícies.
					<?php }else{ ?>
					Posts Arxive.
                    <?php } ?>
                </p>
			<?php }elseif ( is_author() ){ ?>
            	<!-- Author CAPTION -->
                <h2>
                    <i class="icon-pencil"></i>&nbsp;
                    <?php $curauth = (get_query_var('author_name')) ? get_user_by('slug', get_query_var('author_name')) : get_userdata(get_query_var('author')); 
					echo $curauth->nickname; ?>
					
                </h2>
                <p>
                	<?php echo $curauth->description; ?>
                </p>
            <?php }elseif ( is_attachment() ){ ?>
            	<!-- Attachment CAPTION -->
                <h2>
                    <i class="icon-picture"></i>&nbsp;
                    <?php echo get_the_title( $post->post_parent ); ?>
                </h2>
                <p>
					<?php if( qtrans_getLanguage() == 'es' ){ $content = 'Archivos adjuntos: <em>' . get_the_title() . '</em>';
                    }elseif( qtrans_getLanguage() == 'ca' ){ $content = "Arxius adjunts: <em>" . get_the_title() . "</em>";
                    }elseif( qtrans_getLanguage() == 'en' ){ $content = 'Attached files: <em>' . get_the_title() . '</em>';
                    }
					echo $content; ?>
                </p>
			<?php } ?>
            <!-- MOCKUPS GLOBAL -->
                <div class="mockup">
                    <span class="mockup_wrapper">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_dragdroid.png" alt="DRAGDROID Android App" class="mockup_base" />
                    </span>
                    <span class="mockup_wrapper">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag.png" alt="DRAG: Video Demostrativo" class="mockup_base" />
                        <span class="mockup_screen mockup_banner"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/layout/mockup_drag_screen_banner.jpg" alt="<?php if( qtrans_getLanguage() == 'es' ){ ?>DRAG Dispositivo de Recursos para Agentes<?php }elseif( qtrans_getLanguage() == 'ca' ){ ?>DRAG Dispositiu de Recursos para Agents<?php }elseif( qtrans_getLanguage() == 'en' ){ ?>DRAG Dispositivo de Recursos para Agentes<?php } ?>" /></span>
                    </span>
                </div>
        	</div>
        </li>
	<?php } ?>
    </ul>
    <?php //ELEMENTS DE NAVEGACIÓ (PEL HOME)
	if ( is_front_page() ) {?>
    <ul class="flex-control-nav">
            <li class="flex-control-nav_drag"><span><i class="icon-desktop"></i></span><em>DRAG</em></li>
            <li class="flex-control-nav_ddroid"><span><i class="icon-mobile-phone"></i><i class="icon-tablet"></i></span><em>DragDroid</em></li>
    </ul>
    <?php } ?>
  </div>
</div>