<?php
/**
 * Flexslider : Carrusel Responsivo
 * Esto es un SNIPPET para incluir dentro de una plantilla de página de WP
 * Las imagenes se colocan en la carpeta "images/slides" del directorio del ChildTheme
 * 
 * Javascript:
<script type="text/javascript" charset="utf-8">
  $(window).load(function() {
    $('.flexslider').flexslider({
          animation: "slide",
          controlsContainer: ".flex-container"
    });
  });
</script>

*
* Opciones:
namespace: "flex-",             //{NEW} String: Prefix string attached to the class of every element generated by the plugin
selector: ".slides > li",       //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
animation: "fade",              //String: Select your animation type, "fade" or "slide"
easing: "swing",               //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
direction: "horizontal",        //String: Select the sliding direction, "horizontal" or "vertical"
reverse: false,                 //{NEW} Boolean: Reverse the animation direction
animationLoop: true,             //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
smoothHeight: false,            //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode
startAt: 0,                     //Integer: The slide that the slider should start on. Array notation (0 = first slide)
slideshow: true,                //Boolean: Animate slider automatically
slideshowSpeed: 7000,           //Integer: Set the speed of the slideshow cycling, in milliseconds
animationSpeed: 600,            //Integer: Set the speed of animations, in milliseconds
initDelay: 0,                   //{NEW} Integer: Set an initialization delay, in milliseconds
randomize: false,               //Boolean: Randomize slide order
 
// Usability features
pauseOnAction: true,            //Boolean: Pause the slideshow when interacting with control elements, highly recommended.
pauseOnHover: false,            //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
useCSS: true,                   //{NEW} Boolean: Slider will use CSS3 transitions if available
touch: true,                    //{NEW} Boolean: Allow touch swipe navigation of the slider on touch-enabled devices
video: false,                   //{NEW} Boolean: If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches
 
// Primary Controls
controlNav: true,               //Boolean: Create navigation for paging control of each slide? Note: Leave true for manualControls usage
directionNav: true,             //Boolean: Create navigation for previous/next navigation? (true/false)
prevText: "Previous",           //String: Set the text for the "previous" directionNav item
nextText: "Next",               //String: Set the text for the "next" directionNav item
 
// Secondary Navigation
keyboard: true,                 //Boolean: Allow slider navigating via keyboard left/right keys
multipleKeyboard: false,        //{NEW} Boolean: Allow keyboard navigation to affect multiple sliders. Default behavior cuts out keyboard navigation with more than one slider present.
mousewheel: false,              //{UPDATED} Boolean: Requires jquery.mousewheel.js (https://github.com/brandonaaron/jquery-mousewheel) - Allows slider navigating via mousewheel
pausePlay: false,               //Boolean: Create pause/play dynamic element
pauseText: 'Pause',             //String: Set the text for the "pause" pausePlay item
playText: 'Play',               //String: Set the text for the "play" pausePlay item
 
// Special properties
controlsContainer: "",          //{UPDATED} Selector: USE CLASS SELECTOR. Declare which container the navigation elements should be appended too. Default container is the FlexSlider element. Example use would be ".flexslider-container". Property is ignored if given element is not found.
manualControls: "",             //Selector: Declare custom control navigation. Examples would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
sync: "",                       //{NEW} Selector: Mirror the actions performed on this slider with another slider. Use with care.
asNavFor: "",                   //{NEW} Selector: Internal property exposed for turning the slider into a thumbnail navigation for another slider
 
// Carousel Options
itemWidth: 0,                   //{NEW} Integer: Box-model width of individual carousel items, including horizontal borders and padding.
itemMargin: 0,                  //{NEW} Integer: Margin between carousel items.
minItems: 0,                    //{NEW} Integer: Minimum number of carousel items that should be visible. Items will resize fluidly when below this.
maxItems: 0,                    //{NEW} Integer: Maxmimum number of carousel items that should be visible. Items will resize fluidly when above this limit.
move: 0,                        //{NEW} Integer: Number of carousel items that should move on animation. If 0, slider will move all visible items.
 
// Callback API
start: function(){},            //Callback: function(slider) - Fires when the slider loads the first slide
before: function(){},           //Callback: function(slider) - Fires asynchronously with each slider animation
after: function(){},            //Callback: function(slider) - Fires after each slider animation completes
end: function(){},              //Callback: function(slider) - Fires when the slider reaches the last slide (asynchronous)
added: function(){},            //{NEW} Callback: function(slider) - Fires after a slide is added
removed: function(){}           //{NEW} Callback: function(slider) - Fires after a slide is removed

****************************

IDs de Páginas
--------------
INICI -> 5 (FRONT PAGE)
AUTORES -> 7 (HOME)
NOTICIAS -> 9
CONTRATACIÓN -> 11
//
*/
//
// Variables d'Idioma
if (function_exists('qtrans_getLanguage')){
	if( qtrans_getLanguage() == 'es' ){
		$conferencias = 'Conferencias de Autor';
		$autores = 'Autores';
	}elseif( qtrans_getLanguage() == 'ca' ){
		$conferencias = 'Conferències d\'Autor';
		$autores = 'Autors';
	}else{
		$conferencias = 'Author Conferences';
		$autores = 'Authors';
	}
}else{//Not activeQtrans
	$conferencias = 'Conferencias de Autor';
	$autores = 'Autores';
}
//
// Plugin Aviso Legal
$web_array = get_option('legal_web');
 if ( isset($web_array['id_legal']) && $web_array['id_legal'] != '' ){$id_legal = $web_array['id_legal'];}else{$id_legal = '9999';}
?>
<?php //*********************  ESTRUCTURA GLOBAL ***************************** ?>
<section id="fold" class="flex-container">
  <div class="flexslider loading">
    <ul class="slides <?php //if ( is_404() || is_search() || is_page() && !(is_page(array('4','7','9','13'))) || is_home() || is_single() || is_archive() ) { echo 'compact_header'; } ?>">
	<?php // SLIDES ******************************************************* ?>
	<?php 
    //
    // PÀGINA D'INICI *******************************
    // FRONT PAGE ***************** (ID = 5)
	if (is_front_page()) {?>
    <!-- Elige en que pagina aparece >>>>> PÀGINA D'INICI  ******    -->
        <li id="slide_global">
            <img src="<?php echo get_stylesheet_directory_uri() . '/images/slides/next_front.jpg" alt="NEXT ' . $conferencias . '" class="img_fullback'; ?>" />
            <div class="flex-caption">
      			<?php global $page, $paged; ?>
                <h2>
                	<?php
					if (function_exists('qtrans_getLanguage')){ 
						if( qtrans_getLanguage() == 'es' ){
							$metafield = get_post_meta(165, 'metadescription_es', true);
						}elseif( qtrans_getLanguage() == 'ca' ){
							$metafield = get_post_meta(165, 'metadescription_ca', true);
						}else{
							$metafield = get_post_meta(165, 'metadescription_en', true);
						}
					}else{//no qTranslate
						$metafield = get_post_meta(165, 'metadescription_es', true);
					}
					if (!empty ($metafield)){ 
						$content = $metafield;
					}else{ 
						$content = get_bloginfo('description');} 
					echo $content;?>      
                </h2>
				<a href="<?php echo get_home_url() . '/autores/'; ?>" target="_self" class="calltoact animated">
					<i class="fa fa-angle-right fr animated"></i>
				<?php
					if (function_exists('qtrans_getLanguage')){ 
						if( qtrans_getLanguage() == 'es' ){
							$calltoact = 'Conoce a los Autores';
						}elseif( qtrans_getLanguage() == 'ca' ){
							$calltoact = 'Coneix als Autors';
						}else{
							$calltoact = 'Meet\'em all';
						}
					}else{//no qTranslate
						$calltoact = 'Conoce a los Autores';
					}
					echo $calltoact;?> 
				</a>
        	</div>
        </li>
    <?php 
    //
    // PÀGINA AUTORES *******************************
    // HOME PAGE***************** (ID = 7) [AUTORES]
	} elseif ( is_home()){?>
    <!-- Elige en que pagina aparece >>>>> PÀGINA D'AUTORS  ******    -->
        <li id="onlyslide slide_autors">
            <img src="<?php echo get_stylesheet_directory_uri() . '/images/slides/next_autores.jpg" alt="' . $autores . ': NEXT ' . $conferencias . '" class="img_fullback'; ?>" />
            <div class="flex-caption">
      			<?php global $page, $paged; ?>
                <h2>
					<?php echo $autores; ?>
                </h2>
				<h3>
                	<?php
					if (function_exists('qtrans_getLanguage')){ 
						if( qtrans_getLanguage() == 'es' ){
							$metafield = get_post_meta(7, 'metadescription_es', true);
						}elseif( qtrans_getLanguage() == 'ca' ){
							$metafield = get_post_meta(7, 'metadescription_ca', true);
						}else{
							$metafield = get_post_meta(7, 'metadescription_en', true);
						}
					}else{//no qTranslate
						$metafield = get_post_meta(7, 'metadescription_es', true);
					}
					if (!empty ($metafield)){ 
						$content = $metafield;
					}else{ 
						$content = get_bloginfo('name') . ' ' . get_bloginfo('description');} 
					echo $content;?>      
                </h3>
        	</div>
        </li>
    <?php 
	// PÀGINA CONTRATACIÓN *******************************
    // ************************** (ID = 11)
	} elseif (is_page(11)) {?>
	<!-- Elige en que pagina aparece >>>>> PÀGINA CONTRATACIÓN  ******    -->
        <li id="onlyslide slide_global">
            <img src="<?php echo get_stylesheet_directory_uri() . '/images/slides/next_contratacion.jpg" alt="' . get_the_title()  . ': NEXT ' . $conferencias . '" class="img_fullback'; ?>" />
            <div class="flex-caption">
      			<?php global $page, $paged; ?>
                <h2>
					<?php echo get_the_title(); ?>
                </h2>
                <h3>
                	<?php
					if (function_exists('qtrans_getLanguage')){ 
						if( qtrans_getLanguage() == 'es' ){
							$metafield = get_post_meta(11, 'metadescription_es', true);
						}elseif( qtrans_getLanguage() == 'ca' ){
							$metafield = get_post_meta(11, 'metadescription_ca', true);
						}else{
							$metafield = get_post_meta(11, 'metadescription_en', true);
						}
					}else{//no qTranslate
						$metafield = get_post_meta(11, 'metadescription_es', true);
					}
					if (!empty ($metafield)){ 
						$content = $metafield;
					}else{ 
						$content = get_bloginfo('name') . ' ' . get_bloginfo('description');
					}
					echo $content; ?>      
                </h3>
        	</div>
        </li>
	<?php 
	// PÀGINA AVISO LEGAL *******************************
    // ************************** (ID = Auto)
	} elseif (is_page($id_legal)) {?>
	<!-- Elige en que pagina aparece >>>>> PÀGINA CONTRATACIÓN  ******    -->
        <li id="onlyslide slide_global">
            <img src="<?php echo get_stylesheet_directory_uri() . '/images/slides/next_aviso_legal.jpg" alt="' . get_the_title()  . ': NEXT ' . $conferencias . '" class="img_fullback'; ?>" />
            <div class="flex-caption">
      			<?php global $page, $paged; ?>
                <h2>
					<?php echo get_the_title(); ?>
                </h2>
                <h3>
                	<?php
					if (function_exists('qtrans_getLanguage')){ 
						if( qtrans_getLanguage() == 'es' ){
							$metafield = get_post_meta($id_legal, 'metadescription_es', true);
						}elseif( qtrans_getLanguage() == 'ca' ){
							$metafield = get_post_meta($id_legal, 'metadescription_ca', true);
						}else{
							$metafield = get_post_meta($id_legal, 'metadescription_en', true);
						}
					}else{//no qTranslate
						$metafield = get_post_meta($id_legal, 'metadescription_es', true);
					}
					if (!empty ($metafield)){ 
						$content = $metafield;
					}else{ 
						$content = get_bloginfo('name') . ' ' . get_bloginfo('description');
					}
					echo $content; ?>      
                </h3>
        	</div>
        </li>
	<?php
    // PAGE *****************  (amb l'array descartem les pàgines especifiques)  . Primer condicional per condiciones legales
	} elseif (is_page() && !is_page(array(5,7,9,11,$id_legal))) { 
		// PÀGINA AVISO LEGAL *******************************
		// ************************** (ID = Auto)
		?>
		<!-- Elige en que pagina aparece >>>>> PAGINAS GLOBAL  ******    -->
		<li id="onlyslide slide_global">
			<img src="<?php echo get_stylesheet_directory_uri() . '/images/slides/next_global.jpg" alt="' . get_the_title()  . ': NEXT ' . $conferencias . '" class="img_fullback'; ?>" />
			<div class="flex-caption">
				<?php global $page, $paged; ?>
				<h2>
					<?php echo get_the_title(); ?>
				</h2>
				<h3>
					<?php
					if (function_exists('qtrans_getLanguage')){ 
						if( qtrans_getLanguage() == 'es' ){
							$metafield = get_post_meta(get_queried_object_id(), 'metadescription_es', true);
						}elseif( qtrans_getLanguage() == 'ca' ){
							$metafield = get_post_meta(get_queried_object_id(), 'metadescription_ca', true);
						}else{
							$metafield = get_post_meta(get_queried_object_id(), 'metadescription_en', true);
						}
					}else{//no qTranslate
						$metafield = get_post_meta(get_queried_object_id(), 'metadescription_es', true);
					}
					if (!empty ($metafield)){ 
						$content = $metafield;
					}else{ 
						$content = get_bloginfo('name') . ' ' . get_bloginfo('description');
					}
					echo $content; ?>      
				</h3>
			</div>
		</li>
	<?php
	// ARCHIVE ***************** 
	} elseif (is_archive() && !is_author()) { 
		// ARCHIVO DE AUTORES**************
		if (!is_post_type_archive('news')){
			// CATEGORY ******************* 
			if (is_category()) { ?>
		<!-- Elige en que pagina aparece >>>>> Autores -> Categoría ******    -->
        <li id="onlyslide slide_autors">
			<?php
			$queried_object = get_queried_object(); 
			$taxonomy = $queried_object->taxonomy;
			$term_id = $queried_object->term_id;
			$term_title = single_cat_title( '', false); 
			if ( $term_id == 4 ) { $cat_img = 'slide_cat_empresa';
			}elseif ( $term_id == 6 ) { $cat_img = 'slide_cat_salud';
			}elseif ( $term_id == 10 ) { $cat_img = 'slide_cat_ciencia';
			}elseif ( $term_id == 11 ) { $cat_img = 'slide_cat_psicologia';
			}elseif ( $term_id == 12 ) { $cat_img = 'slide_cat_educacion';
			}else { $cat_img = 'next_autores'; }
			echo '<img src="' . get_stylesheet_directory_uri() . '/images/slides/' . $cat_img . '.jpg" alt="' . $term_title . '" class="img_fullback" />';
            ?>
            <div class="flex-caption caption-postcat">
                <h2>
                	<?php 
                    // we will use the first term to load ACF data from 
					$iconcat = get_field('cat_icon', $taxonomy . '_' . $term_id);
					if (function_exists('qtrans_getLanguage')){ 
						if( qtrans_getLanguage() == 'es' ){ $content_h = 'Autores expertos en ';
						}elseif( qtrans_getLanguage() == 'ca' ){ $content_h = 'Autors experts en ';
						}elseif( qtrans_getLanguage() == 'en' ){ $content_h = 'Expert Authors ';
						} 
					}else{
						$content_h = 'Autores expertos en ';
					} ?>
                    <?php echo $content_h;?><em><?php single_cat_title(); ?></em>
                </h2>
                <h3>
				<?php  if (function_exists('qtrans_getLanguage')){ 
					if ( !('' == category_description()) ){
						$content = apply_filters('archive_meta', category_description(), 'qtranslate');
						echo strip_tags($content);
					}
				}else{
					$content = category_description();
					echo strip_tags($content);
				}?>
                </h3>
        	</div>
        </li>
			<?php
            // TAG ************************ 
			} elseif (is_tag()) { ?>
		<!-- Elige en que pagina aparece >>>>> Autores -> Etiquetas ******    -->
        <li id="onlyslide slide_autors">
            <img src="<?php echo get_stylesheet_directory_uri() . '/images/slides/next_global.jpg" alt="' . single_tag_title('', false) . '" class="img_fullback'; ?>" />
            <div class="flex-caption caption-postcat">
                <h2>
                	<?php 
					if (function_exists('qtrans_getLanguage')){ 
						if( qtrans_getLanguage() == 'es' ){ $content_h = 'Autores expertos en ';
						}elseif( qtrans_getLanguage() == 'ca' ){ $content_h = 'Autors experts en ';
						}elseif( qtrans_getLanguage() == 'en' ){ $content_h = 'Expert Authors ';
						} 
					}else{
						$content_h = 'Autores expertos en ';
					}
					echo $content_h . '<em>' . single_tag_title('', false) . '</em>';
                    ?>
                </h2>
				<?php if (tag_description() != ''){ echo '<h3>' . tag_description() . '</h3>'; } ?>
        	</div>
        </li> 
			<?php
            // DATE ************************ 
			} elseif ( is_date() ){ ?>
        <!-- Elige en que pagina aparece >>>>> Autores -> Cronologia ******    -->
        <li id="onlyslide slide_autors">
            <img src="<?php echo get_stylesheet_directory_uri() . '/images/slides/next_global.jpg" alt="NEXT ' . $conferencias . '" class="img_fullback'; ?>" />
            <div class="flex-caption caption-postcat">
                <h2>
                    <i class="fa fa-calendar"></i>&nbsp;
					<?php if  (is_day()) { global $post; echo get_the_time(get_option('date_format')); ?>
                    <?php }elseif  (is_month()) { global $post; echo get_the_time('F Y'); ?>
                    <?php }elseif  (is_year()) { global $post; echo get_the_time('Y'); ?>
                    <?php } ?>
                </h2>
                <h3>
                	<?php if (function_exists('qtrans_getLanguage')){ 
						if( qtrans_getLanguage() == 'es' ){ echo 'Archivo cronológico de Autores.';
						}elseif( qtrans_getLanguage() == 'ca' ){ echo 'Arxiu cronològic d\' Autors.';
						}elseif( qtrans_getLanguage() == 'en' ){ echo 'Authors archive.';
						} 
					}else{
						echo 'Archivo cronológico de Autores.';
					} ?>
                </h3>
        	</div>
        </li> 
			<?php
            // CUSTOM POST TAGS NEWS  ******************* 
			} elseif (is_tax()) { ?>
		<!-- Elige en que pagina aparece >>>>> News -> Tag ******    -->
        <li id="onlyslide slide_news">
            <img src="<?php echo get_stylesheet_directory_uri() . '/images/slides/next_news.jpg" alt="' . single_tag_title('', false) . '" class="img_fullback'; ?>" />
            <div class="flex-caption caption-postcat">
                <h2>
                    <?php if (function_exists('qtrans_getLanguage')){ 
						if( qtrans_getLanguage() == 'es' ){ $content_h = 'Noticias archivadas en ';
						}elseif( qtrans_getLanguage() == 'ca' ){ $content_h = 'Notícies archivades a ';
						}elseif( qtrans_getLanguage() == 'en' ){ $content_h = 'News archive: ';
						} 
					}else{
						$content_h = 'Noticias archivadas en ';
					} 
					echo $content_h . '<em>' . single_cat_title('', false) . '</em>';
					?>
                </h2>
                <?php if (tag_description() != ''){ echo '<h3>' . tag_description() . '</h3>'; } ?>
        	</div>
        </li> 
			<?php 
			}
		// ARCHIVO DE NOTICIAS************** (NEWS) 
		}else{
			// DATE ************************ 
			if ( is_date() ){ ?>
		<!-- Elige en que pagina aparece >>>>> Noticias -> Cronologia ******    -->
        <li id="onlyslide slide_news">
            <img src="<?php echo get_stylesheet_directory_uri() . '/images/slides/next_news.jpg" alt="NEXT ' . $conferencias . '" class="img_fullback'; ?>" />
            <div class="flex-caption caption-postcat">
                <h2>
                    <i class="fa fa-calendar"></i>&nbsp;
					<?php if  (is_day()) { global $post; echo get_the_time(get_option('date_format')); ?>
                    <?php }elseif  (is_month()) { global $post; echo get_the_time('F Y'); ?>
                    <?php }elseif  (is_year()) { global $post; echo get_the_time('Y'); ?>
                    <?php } ?>
                </h2>
                <h3>
                	<?php if (function_exists('qtrans_getLanguage')){ 
						if( qtrans_getLanguage() == 'es' ){ echo 'Archivo cronológico de Noticias.';
						}elseif( qtrans_getLanguage() == 'ca' ){ echo 'Arxiu cronològic de Notícies.';
						}elseif( qtrans_getLanguage() == 'en' ){ echo 'News archive.';
						} 
					}else{
						echo 'Archivo cronológico de Noticias.';
					}?>
                </h3>
        	</div>
        </li> 
			<?php 
            }else{
			//Página FRONTPAGE de Noticias [ID = 9] ?>
		<!-- Elige en que pagina aparece >>>>> Noticias -> Cronologia ******    -->
        <li id="onlyslide slide_news">
            <?php if (function_exists('qtrans_getLanguage')){ 
				if( qtrans_getLanguage() == 'es' ){ $news = 'NOTICIAS';
				}elseif( qtrans_getLanguage() == 'ca' ){ $news = 'NOTÍCIES';
				}elseif( qtrans_getLanguage() == 'en' ){ $news = 'NEWS';
				} 
			}else{ //No qTrqanslate
				$news = 'NOTICIAS';
			}?>
            <img src="<?php echo get_stylesheet_directory_uri() . '/images/slides/next_news.jpg" alt="' . $news . ': NEXT ' . $conferencias . '" class="img_fullback'; ?>" />
            <div class="flex-caption caption-postcat">
                <h2>
                	<?php echo $news; ?>
                </h2>
                <h3>
                	<?php if (function_exists('qtrans_getLanguage')){ 
						if( qtrans_getLanguage() == 'es' ){ echo '<em>NEXT </em>' . $conferencias;
						}elseif( qtrans_getLanguage() == 'ca' ){ echo '<em>NEXT </em>' . $conferencias;
						}elseif( qtrans_getLanguage() == 'en' ){ echo '<em>NEXT </em>' . $conferencias;
						} 
					}else{
						echo '<em>NEXT </em>' . $conferencias;
					}?>
                </h3>
        	</div>
        </li> 
			<?php
            }
		}
	//
	// POST ***************** (AUTORES)
	//
	} elseif (is_single() && !is_singular( 'news' ) && !is_singular( 'tribe_events' ) && !is_attachment() && !is_archive()) { ?>
	<!-- Elige en que pagina aparece >>>>> Página de Autor ******    -->
    <li id="onlyslide slide_autors">
        <?php global $post;
        $category = get_the_category($post->ID);
        $category_id = $category[0]->cat_ID;
        //if (function_exists('qtrans_getLanguage')){ $category_description = _e($category[0]->category_description, 'qtranslate'); }else{$category_description = ($category[0]->category_description);}
        if ( $category_id == 4 ) { $cat_img = 'slide_cat_empresa';
        }elseif ( $category_id == 6 ) { $cat_img = 'slide_cat_salud';
        }elseif ( $category_id == 10 ) { $cat_img = 'slide_cat_ciencia';
        }elseif ( $category_id == 11 ) { $cat_img = 'slide_cat_psicologia';
        }elseif ( $category_id == 12 ) { $cat_img = 'slide_cat_educacion';
        }else { $cat_img = 'next_autores'; }
        echo '<img src="' . get_stylesheet_directory_uri() . '/images/slides/' . $cat_img . '.jpg" alt="' . $category[0]->cat_name . '" class="img_fullback" />';?>
        <div class="flex-caption caption-postcat">
            <h2><?php global $post;
                // load all 'category' terms for the post
                $terms = get_the_terms($post->ID, 'category');
                // we will use the first term to load ACF data from 
                if( !empty($terms) ){
                    $term = array_pop($terms);
                    $iconcat = get_field('cat_icon', 'category_' . $term->term_id );		 
                }
                echo '<a href="' . get_category_link($category[0]->term_id ) . '" target="_self" title="' .  $category[0]->cat_name . '" class="animated"> <em><i class="fa ' . $iconcat . '"></i>&nbsp;&nbsp;' .  $category[0]->cat_name . '</em></a>';?>
            </h2>
        </div>
    </li>
    <?php 
	//// POST ***************** (TYPE = NEWS)
	} elseif (is_singular( 'news' )) { ?> 
	<!-- Elige en que pagina aparece >>>>> Página de Noticia ******    -->
    <li id="onlyslide slide_news">
		<?php 
		if (function_exists('qtrans_getLanguage')){ 
			if( qtrans_getLanguage() == 'es' ){ $news = 'NOTICIAS';
			}elseif( qtrans_getLanguage() == 'ca' ){ $news = 'NOTÍCIES';
			}elseif( qtrans_getLanguage() == 'en' ){ $news = 'NEWS';
			} 
		}else{
			$news = 'NOTICIAS';
		}
        echo '<img src="' . get_stylesheet_directory_uri() . '/images/slides/next_news.jpg" alt="' . $news . ': NEXT ' . $conferencias . '" class="img_fullback" />';?>
        <div class="flex-caption caption-postcat">
            <h2><?php echo $news; ?></h2>
            <h3>
            	<?php if (function_exists('qtrans_getLanguage')){ 
					if( qtrans_getLanguage() == 'es' ){ echo '<em>NEXT </em>' . $conferencias;
					}elseif( qtrans_getLanguage() == 'ca' ){ echo '<em>NEXT </em>' . $conferencias;
					}elseif( qtrans_getLanguage() == 'en' ){ echo '<em>NEXT </em>' . $conferencias;
					} 
				}else{
					echo '<em>NEXT </em>' . $conferencias;
				}?>
            </h3>
        </div>
    </li>
	<?php 
	//// POST ***************** (TYPE = EVENTS)
	} elseif (is_singular( 'tribe_events' )) { ?> 
	<!-- Elige en que pagina aparece >>>>> Página de Evento ******    -->
    <li id="onlyslide slide_news">
		<?php 
		if (function_exists('qtrans_getLanguage')){ 
			if( qtrans_getLanguage() == 'es' ){ $event = 'EVENTOS';
			}elseif( qtrans_getLanguage() == 'ca' ){ $event = 'EVENTS';
			}elseif( qtrans_getLanguage() == 'en' ){ $event = 'EVENTS';
			} 
		}else{
			$event = 'EVENTOS';
		}
        echo '<img src="' . get_stylesheet_directory_uri() . '/images/slides/next_event.jpg" alt="' . $event . ': NEXT ' . $conferencias . '" class="img_fullback" />';?>
        <div class="flex-caption caption-postcat">
            <h2><?php echo $event; ?></h2>
            <h3>
            	<?php if (function_exists('qtrans_getLanguage')){ 
					if( qtrans_getLanguage() == 'es' ){ echo '<em>NEXT </em>' . $conferencias;
					}elseif( qtrans_getLanguage() == 'ca' ){ echo '<em>NEXT </em>' . $conferencias;
					}elseif( qtrans_getLanguage() == 'en' ){ echo '<em>NEXT </em>' . $conferencias;
					} 
				}else{
					echo '<em>NEXT </em>' . $conferencias;
				}?>
            </h3>
        </div>
    </li>
	<?php 
	//// PAGINA CALENDAR ***************** (TYPE = EVENTS)
	} elseif (tribe_is_month()) { ?> 
	<!-- Elige en que pagina aparece >>>>> Página de Evento ******    -->
    <li id="onlyslide slide_news">
		<?php 
		if (function_exists('qtrans_getLanguage')){ 
			if( qtrans_getLanguage() == 'es' ){ $event = 'CONFERENCIAS y EVENTOS';
			}elseif( qtrans_getLanguage() == 'ca' ){ $event = 'CONFERÈNCIES i EVENTS';
			}elseif( qtrans_getLanguage() == 'en' ){ $event = 'SPEACHES & EVENTS';
			} 
		}else{
			$event = 'CONFERENCIAS y EVENTOS';
		}
        echo '<img src="' . get_stylesheet_directory_uri() . '/images/slides/next_event.jpg" alt="' . $event . ': NEXT ' . $conferencias . '" class="img_fullback" />';?>
        <div class="flex-caption caption-postcat">
            <h2><?php echo $event; ?></h2>
            <h3>
            	<?php if (function_exists('qtrans_getLanguage')){ 
				if( qtrans_getLanguage() == 'es' ){ echo '<em>NEXT </em>' . $conferencias;
				}elseif( qtrans_getLanguage() == 'ca' ){ echo '<em>NEXT </em>' . $conferencias;
				}elseif( qtrans_getLanguage() == 'en' ){ echo '<em>NEXT </em>' . $conferencias;
				} 
			}else{
				echo '<em>NEXT </em>' . $conferencias;
			}?>
            </h3>
        </div>
    </li>
    <?php
	// AUTOR de POSTS *****************
	}elseif (is_author()) {?> 
	<!-- Elige en que pagina aparece >>>>> Página de Autor (Redactor) ******    -->
    <li id="onlyslide slide_global">
		<?php 
        echo '<img src="' . get_stylesheet_directory_uri() . '/images/slides/next_global.jpg" alt="NEXT ' . $conferencias . '" class="img_fullback" />';
		?>
        <div class="flex-caption caption-postcat">
            <h2>
                <?php $curauth = (get_query_var('author_name')) ? get_user_by('slug', get_query_var('author_name')) : get_userdata(get_query_var('author')); 
                echo $curauth->nickname; ?>
            </h2>
            <h3>
                <?php echo $curauth->description; ?>
            </h3>
        </div>
    </li>
    <?php
	// SEARCH RESULTS ***************** 
	}elseif (is_search()) {?> 
	<!-- Elige en que pagina aparece >>>>> Página de Busqueda ******    -->
    <li id="onlyslide slide_global">
		<?php 
        echo '<img src="' . get_stylesheet_directory_uri() . '/images/slides/next_search.jpg" alt="NEXT ' . $conferencias . '" class="img_fullback" />';
		?>
        <div class="flex-caption caption-postcat">
            <h2>
				<?php if (function_exists('qtrans_getLanguage')){ 
					if( qtrans_getLanguage() == 'es' ){ echo 'Resultados de Búsqueda';
					}elseif( qtrans_getLanguage() == 'ca' ){ echo 'Resultats de la Cerca';
					}elseif( qtrans_getLanguage() == 'en' ){ echo 'Search Results';
					} 
				}else{
					echo 'Resultados de Búsqueda';
				}?>
            </h2>
            <h3>
            	<i class="fa fa-search"></i>&nbsp;<?php the_search_query(); ?>
            </h3>
        </div>
    </li>
    <?php
	//ATTACHMENT *********************
	}elseif (is_attachment()) {?> 
	<!-- Elige en que pagina aparece >>>>> Archivos Adjuntos ******    -->
    <li id="onlyslide slide_global">
		<?php 
        echo '<img src="' . get_stylesheet_directory_uri() . '/images/slides/next_global.jpg" alt="NEXT ' . $conferencias . '" class="img_fullback" />';
		?>
        <div class="flex-caption caption-postcat">
            <h2>
                <i class="fa fa-file-image-o"></i>&nbsp;
                <?php echo get_the_title(); ?>
            </h2>
            <h3>
                <?php if (function_exists('qtrans_getLanguage')){ 
					if( qtrans_getLanguage() == 'es' ){ $content = 'Archivos adjuntos de: <em>"' . get_the_title( $post->post_parent ) . '"</em>';
					}elseif( qtrans_getLanguage() == 'ca' ){ $content = 'Arxius adjunts de: <em>"' . get_the_title( $post->post_parent ) . '"</em>';
					}elseif( qtrans_getLanguage() == 'en' ){ $content = 'Attached files from: <em>"' . get_the_title( $post->post_parent ) . '"</em>';
					} 
				}else{
					$content = 'Archivos adjuntos de: <em>"' . get_the_title( $post->post_parent ) . '"</em>';
				}
				echo $content;?>
            </h3>
        </div>
    </li>
    <?php
	// PAGINA 404
	}elseif (is_404()) {?> 
	<!-- Elige en que pagina aparece >>>>> Error 404 ******    -->
    <li id="onlyslide slide_global">
		<?php 
        echo '<img src="' . get_stylesheet_directory_uri() . '/images/slides/next_global.jpg" alt="NEXT ' . $conferencias . '" class="img_fullback" />';
		?>
        <div class="flex-caption caption-postcat">
            <h2>
                <?php if (function_exists('qtrans_getLanguage')){ 
					if( qtrans_getLanguage() == 'es' ){ $content = 'LA PÁGINA NO EXISTE';
					}elseif( qtrans_getLanguage() == 'ca' ){ $content = 'LA PÀGINA NO EXISTEIX';
					}elseif( qtrans_getLanguage() == 'en' ){ $content = 'PAGE NOT FOUND';
					} 
				}else{
					$content = 'LA PÁGINA NO EXISTE';
				}
				echo $content;?>
            </h2>
            <h3>
                <?php if (function_exists('qtrans_getLanguage')){ 
					if( qtrans_getLanguage() == 'es' ){ $content2 = 'Lo sentimos pero no encontramos este contenido.';
					}elseif( qtrans_getLanguage() == 'ca' ){ $content2 = 'Ho sentim però no trobem aquest contingut.';
					}elseif( qtrans_getLanguage() == 'en' ){ $content2 = 'Sorry but we can\'t find this page.';
					} 
				}else{
					$content2 = 'Lo sentimos pero no encontramos este contenido.';
				}
				echo $content2;?>
            </h3>
        </div>
    </li>
    <?php
	// GENERAL ***************** 
	} else {?> 
	<!-- Elige en que pagina aparece >>>>> Error 404 ******    -->
    <li id="onlyslide slide_global">
		<?php 
        echo '<img src="' . get_stylesheet_directory_uri() . '/images/slides/next_global.jpg" alt="NEXT ' . $conferencias . '" class="img_fullback" />';
		?>
        <div class="flex-caption caption-postcat">
            <h2>
                <?php if (function_exists('qtrans_getLanguage')){ 
					if( qtrans_getLanguage() == 'es' ){ $content = 'LA PÁGINA NO EXISTE';
					}elseif( qtrans_getLanguage() == 'ca' ){ $content = 'LA PÀGINA NO EXISTEIX';
					}elseif( qtrans_getLanguage() == 'en' ){ $content = 'PAGE NOT FOUND';
					} 
				}else{
					$content = 'LA PÁGINA NO EXISTE';
				}
				echo $content;?>
            </h2>
            <h3>
                <?php if (function_exists('qtrans_getLanguage')){ 
					if( qtrans_getLanguage() == 'es' ){ $content2 = 'Lo sentimos pero no encontramos este contenido.';
					}elseif( qtrans_getLanguage() == 'ca' ){ $content2 = 'Ho sentim però no trobem aquest contingut.';
					}elseif( qtrans_getLanguage() == 'en' ){ $content2 = 'Sorry but we can\'t find this page.';
					} 
				}else{
					$content2 = 'Lo sentimos pero no encontramos este contenido.';
				}
				echo $content2;?>
            </h3>
        </div>
    </li>
	<?php } ?>
    </ul>
    <?php //ELEMENTS DE NAVEGACIÓ (PEL HOME)
	/*if ( is_front_page() ) {
    <ul class="flex-control-nav">
		<li class="flex-control-nav_drag"><span><i class="icon-desktop"></i></span><em>DRAG</em></li>
		<li class="flex-control-nav_ddroid"><span><i class="icon-mobile-phone"></i><i class="icon-tablet"></i></span><em>DragDroid</em></li>
    </ul>
     }*/ 
	 ?>
  </div>
</section>